version: '2'

services:

    #################### Database  ##########################
    rnan_mariadb:
        container_name: rnan_mariadb
        image: bitnami/mariadb:10.2
        ports:
          - 3307:3306
        environment:
          - MARIADB_ROOT_PASSWORD=password
          - MARIADB_USER=rnan_usr
          - MARIADB_PASSWORD=kibnoi
          - MARIADB_DATABASE=rnanlab_db
        volumes:
          - ./dockers/db:/bitnami

   #################### php-fpm-laravel  ##########################
    rnanlab:
        container_name: rnanlab
        image: bitnami/php-fpm:7.3.10
        depends_on:
            - rnan_mariadb
        volumes:
          - ./dockers/web/phpfpm/php-fpm.conf:/opt/bitnami/php/etc/php-fpm.conf
          - ./dockers/web/phpfpm/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf
          - ./www:/app

    #################### nginx  ##########################
    nginx:
        container_name: nginx
        image: bitnami/nginx:1.16
        ports:
          - 80:8080
          - 443:8443
        depends_on:
            - rnanlab
        volumes:
            - ./dockers/web/nginx:/bitnami/nginx
            - ./dockers/certs:/opt/bitnami/certs
            - ./dockers/web/nginx/nginx-vhost/rnanlab.conf:/opt/bitnami/nginx/conf/server_blocks/rnanlab.conf
            - ./www:/app
